### ISSUE TITLE
Quality Control

### ISSUE THREAD

**Issue by Lydia-Steiner** [datascience-mobi-2022/2022-topic-04-team-02#1]
Let me know which of these Chips you find good and which we should remove :
![GSM701716_Mouse_E7 5_1 CEL](https://user-images.githubusercontent.com/104202526/168450827-6396ce0a-c59b-4ea6-90f7-553a98316366.png)
![GSM701717_Mouse_E7 5_2 CEL](https://user-images.githubusercontent.com/104202526/168450829-bb5cf29c-24d9-4de7-bf5c-078a85b72a50.png)
![GSM701718_Mouse_E7 5_3 CEL](https://user-images.githubusercontent.com/104202526/168450830-8fa8c22a-6cc2-478b-910c-be9b10418e95.png)
![GSM701719_Mouse_E8 5_1 CEL](https://user-images.githubusercontent.com/104202526/168450831-94eb6393-4e4a-4973-94d6-73cf1536c49c.png)
![GSM701720_Mouse_E8 5_2 CEL](https://user-images.githubusercontent.com/104202526/168450832-f01ff37f-e25e-47f2-be67-9ab1e09621d5.png)
![GSM701721_Mouse_E8 5_3 CEL](https://user-images.githubusercontent.com/104202526/168450834-42132d4d-ae96-4fe8-a989-c8f398831aed.png)
![GSM701722_Mouse_E9 5_1 CEL](https://user-images.githubusercontent.com/104202526/168450835-fd1e6f2a-f9ba-4077-929c-a1db634b8625.png)
![GSM701723_Mouse_E9 5_2 CEL](https://user-images.githubusercontent.com/104202526/168450836-2978ae2f-ae74-426a-9438-3fa667eb3c70.png)
![GSM701724_Mouse_E9 5_3 CEL](https://user-images.githubusercontent.com/104202526/168450837-e7732e31-8c31-4c9e-ae7b-39cd14716f53.png)
![GSM701725_Mouse_E10 5_1 CEL](https://user-images.githubusercontent.com/104202526/168450838-c2edb8bb-39fd-4c3e-975d-228592c11355.png)
![GSM701726_Mouse_E10 5_2 CEL](https://user-images.githubusercontent.com/104202526/168450839-ecb94cfa-bf9b-45fc-b23f-f5c07dbf2da9.png)
![GSM701727_Mouse_E10 5_3 CEL](https://user-images.githubusercontent.com/104202526/168450840-c657cd95-bbe4-46f2-831f-b295c18e266b.png)
![GSM701728_Mouse_E12 5_1 CEL](https://user-images.githubusercontent.com/104202526/168450841-7ef79eb1-9bf2-4250-8e52-7e7363e85a5d.png)
![GSM701729_Mouse_E12 5_2 CEL](https://user-images.githubusercontent.com/104202526/168450843-dcca9386-9dc9-40e6-a84e-8e9c39b73539.png)
![GSM701730_Mouse_E14 5_1 CEL](https://user-images.githubusercontent.com/104202526/168450846-2a5b6b7b-c6a6-4b5b-b1ac-28b9b48fa7ac.png)
![GSM701731_Mouse_E14 5_2 CEL](https://user-images.githubusercontent.com/104202526/168450848-be9b0d70-80ad-4772-8e45-5c90aea07e77.png)
![GSM701732_Mouse_E16 5_1 CEL](https://user-images.githubusercontent.com/104202526/168450850-03fb0eb5-81ae-4c21-9933-35020e11ae36.png)
![GSM701733_Mouse_E16 5_2 CEL](https://user-images.githubusercontent.com/104202526/168450851-e0f66c72-00bc-4aea-9ac3-572c27eb86c2.png)
![GSM701734_Mouse_E18 5_1 CEL](https://user-images.githubusercontent.com/104202526/168450853-a6e56f6c-a7e8-4882-bb63-ad54b311697b.png)
![GSM701735_Mouse_E18 5_2 CEL](https://user-images.githubusercontent.com/104202526/168450855-8a9a762c-85de-4875-8384-21b507446a2b.png)

**Comment by ninabank** [comment]
Ich finde die sehen alle recht tauglich aus. 1-2 Stück haben allerdings etwas mehr Streifen als der Rest, da weiß ich nicht wie starke Streifen im Rahmen sind.
